In [1]:
import pandas as pd 
import numpy as np

In [15]:
from sklearn.datasets import load_iris

data=load_iris()

X=data.data
y=data.target
y.shape

(150,)

In [6]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.18,random_state=42)

In [8]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [10]:
from sklearn.metrics import classification_report , confusion_matrix
print(f"Confusion Metric: {confusion_matrix(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Confusion Metric: [[ 8  0  0]
 [ 0  9  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        10

    accuracy                           1.00        27
   macro avg       1.00      1.00      1.00        27
weighted avg       1.00      1.00      1.00        27



In [11]:
from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier()

y_pred=model.fit(X_train,y_train).predict(X_test)

In [14]:
print(f"Confusion Metric: {confusion_matrix(y_test,y_pred)}")
print()
print(classification_report(y_test,y_pred))

Confusion Metric: [[ 8  0  0]
 [ 0  9  0]
 [ 0  0 10]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        10

    accuracy                           1.00        27
   macro avg       1.00      1.00      1.00        27
weighted avg       1.00      1.00      1.00        27

